// Date: 07/05/2013 21:36:01
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package uk.co.shadowravengames.smeltersforge.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class TestModel extends ModelBase
{
  //fields
    public static ModelRenderer energyCore;
    public static ModelRenderer holder;
	public static int energyCoreShown = 0;
 
  public TestModel() {
    textureWidth = 64;
    textureHeight = 32;
    
      energyCore = new ModelRenderer(this, 0, 6);
      energyCore.addBox(0F, 0F, 0F, 4, 15, 4);
      energyCore.setRotationPoint(-2F, 9F, -2F);
      energyCore.setTextureSize(64, 32);
      energyCore.mirror = true;
      energyCore.showModel = false;
      setRotation(energyCore, 0F, 0F, 0F);
      
      holder = new ModelRenderer(this, 25, 6);
      holder.addBox(0F, 0F, 0F, 8, 1, 8);
      holder.setRotationPoint(-4F, 16F, -4F);
      holder.setTextureSize(64, 32);
      holder.mirror = true;
      holder.showModel = false;
      setRotation(holder, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    energyCore.render(f5);
    holder.render(f5);
  }
  
  public void renderModel(float f1) {
	energyCore.render(f1);
	holder.render(f1);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z) {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
